### ISSUE TITLE
OpenCore picker fonts too small

### ISSUE THREAD

**Issue by crojack** [chris1111/OpenCore-Theme-Builder#1]
Is it possible to change fonts type and size in OpenCore Resources/Fonts? There isn't any documentation on font.bin files in OC/Resources/Fonts folder, and it's impossible to extract them. How these font.bin and font.png files work?

I have 2k resolution monitor and the fonts appear too small.

![12134526](https://user-images.githubusercontent.com/49529443/232098416-c283297c-76db-4a3d-95c0-1b35a315de6a.png)

![14152903](https://user-images.githubusercontent.com/49529443/232099852-89af8c80-a197-416c-8804-6920f1ff8a05.png)

**Comment by chris1111** [comment]
No way to my knowledge
This theme as nothing to do with OC theme Builder
